name: Java

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
 
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: mvn compile
      working-directory: /home/runner/work/VidClick-API/server
    - name: Run tests
      run: mvn test
      working-directory: /home/runner/work/VidClick-API/server

  

