name: Auto Merge to Main

on:
  push:
    branches:
      - '*'
    exclude:
      - main

jobs:
  open_pull_request:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Create Pull Request
      id: create_pr
      uses: actions/github-script@v5
      with:
        script: |
          const newBranch = context.payload.ref.split('/').slice(2).join('/');
          const title = `Merge ${newBranch} into main`;
          const body = `This pull request merges ${newBranch} into the main branch.`;
    
          const pr = await github.pulls.create({
            owner: context.repo.owner,
            repo: context.repo.repo,
            title: title,
            body: body,
            head: newBranch,
            base: 'main'
          });
          
          console.log(`Pull Request Number: ${pr.data.number}`);
          core.setOutput('pull_request_number', pr.data.number);
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
  merge_to_main:
    runs-on: ubuntu-latest
    needs: open_pull_request
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Merge to Main
      id: merge
      run: |
        pr_number=${{ needs.open_pull_request.outputs.pull_request_number }}
        
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        
        git fetch origin pull/${pr_number}/head:pr-${pr_number}
        git checkout main
        git merge --no-ff pr-${pr_number} -m "Merge pull request #${pr_number}"
        
        git push origin main
    
